### ISSUE TITLE
fyi - website page photon/components broken on safari 8

### ISSUE THREAD

**Issue by marfarma** [connors/photon#57]
The majority of mac users that browse via safari are likely still on safari 8. Doing away with the -webkit- prefix for flex related styles breaks the layout.   You're not alone in this, I've seen several other recently launched sites with the same issue.  Just thought I'd mention it.

It's all the more irritating - especially since, for whatever reason, the recently announced Yosemite Safari 9 update is not listed in the app store at the moment.

**Comment by developit** [comment]
@marfarma This is probably not something that will get fixed - this CSS library is specifically targetted at Chrome because that's the runtime Electron uses.

I'm not sure what @connors' plans are for potentially expanding beyond providing a toolkit for Electron development.  I would consider using Photon in a browser, but I'd probably do it by bundling the CSS, which would mean it would be run through autoprefixer.

**Comment by marfarma** [comment]
I wasn't reporting a problem with Photon, but rather it's website.  This page in particular: http://photonkit.com/components/  There's no reason to expect that someone who just want's to find out what Photon is, should use a particular browser.

If you don't want to fix that either - that's fine.  In that case, maybe alert people using Safari < 9 that the site is best viewed in Chrome, Firefox or an updated version of Safari?  The way it is now gives the wrong impression.

**Comment by connors** [comment]
@marfarma Thanks for the heads up! That's an oversight on my part and I'll get it patched up soon.

**Comment by connors** [comment]
Fixed in 14b3c66. I'll roll this out to the deployed docs soon.
